---
- name: Query Oracle Database Role and Switchover Status
  hosts: ora19cdg02.bwok.org
  tasks:
    - name: Source the bash profile and set environment variables
      shell: |
        # Set Environment Variables
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin

        # Run SQL Commands
        sqlplus -s / as sysdba <<EOF
          startup mount;
          SELECT name, open_mode, database_role FROM v\$database;
        EOF
      register: db_status
      ignore_errors: yes

    - name: Display the database status
      debug:
        msg: "Database Status:\n{{ db_status.stdout }}"
